### ISSUE TITLE
Error during the build

### ISSUE THREAD

**Issue by adfdev** [Akylas/nativescript-opencv#2]
Have this error on build:

`Undefined symbols for architecture x86_64:
  "cv::String::deallocate()", referenced from:
      cv::String::~String() in OpenCVAdditions(OpenCVWrapper.o)
      cv::String::operator=(cv::String const&) in OpenCVAdditions(OpenCVWrapper.o)
  "cv::findContours(cv::_InputOutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)", referenced from:
      +[OpenCVWrapper findContours:::::] in OpenCVAdditions(OpenCVWrapper.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Using build description from disk`

Have tried 

`tns run ios --clean` and `tns update`

**Comment by farfromrefug** [comment]
it seems like OpenCV is not found or not the right version . in the build log it should tell you what version of OpenCV is used. Can you report it here?
