### ISSUE TITLE
Detect corners of document and crop

### ISSUE THREAD

**Issue by adfdev** [Akylas/nativescript-opencv#3]
I know OpenCV very well, but i doubt this plugin is integrated correctly for my use. Can this plugin detect document, crop and fix perspective, or not still to able?

**Comment by farfromrefug** [comment]
it depends how you want to do this. the issue is that on android all JS code runs on the ui thread. so if you want to do it from an image you can do it with a worker. if you want to do it from live camera it won't work.
still some open CV function you might need may not be wrapped  in JS yet.

**Comment by adfdev** [comment]
Not need for live feed but only for still image. Can you help me?

**Comment by farfromrefug** [comment]
You have to look at an OpenCV example and port here.

**Comment by adfdev** [comment]
Are you intend example for C++?

**Comment by farfromrefug** [comment]
Whatever. The idea is to get the called openCV methods and translate it.
